import type {
  MaintenanceWindow,
  ManufacturingOrderDocument,
  PrepareScheduleInput,
  WorkCenterDocument,
  WorkCenterShift,
  WorkOrderDocument,
} from "../reflow/types.js";

const iso = (day: number, hour: number, minute = 0): string =>
  `2026-01-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:${String(
    minute,
  ).padStart(2, "0")}:00.000Z`;

const weekdayShift = (startHour: number, endHour: number): WorkCenterShift[] =>
  [1, 2, 3, 4, 5].map((dayOfWeek) => ({
    dayOfWeek,
    startHour,
    endHour,
  }));

const workCenter = (
  docId: string,
  name: string,
  startHour: number,
  endHour: number,
  maintenanceWindows: MaintenanceWindow[],
): WorkCenterDocument => ({
  docId,
  docType: "workCenter",
  data: {
    name,
    shifts: weekdayShift(startHour, endHour),
    maintenanceWindows,
  },
});

const manufacturingOrder = (
  docId: string,
  manufacturingOrderNumber: string,
  itemId: string,
  quantity: number,
  dueDate: string,
): ManufacturingOrderDocument => ({
  docId,
  docType: "manufacturingOrder",
  data: {
    manufacturingOrderNumber,
    itemId,
    quantity,
    dueDate,
  },
});

const workOrder = ({
  docId,
  workOrderNumber,
  manufacturingOrderId,
  workCenterId,
  startDate,
  endDate,
  durationMinutes,
  isMaintenance = false,
  dependsOnWorkOrderIds = [],
}: {
  docId: string;
  workOrderNumber: string;
  manufacturingOrderId: string;
  workCenterId: string;
  startDate: string;
  endDate: string;
  durationMinutes: number;
  isMaintenance?: boolean;
  dependsOnWorkOrderIds?: string[];
}): WorkOrderDocument => ({
  docId,
  docType: "workOrder",
  data: {
    workOrderNumber,
    manufacturingOrderId,
    workCenterId,
    startDate,
    endDate,
    durationMinutes,
    isMaintenance,
    dependsOnWorkOrderIds,
  },
});

const workCenters: WorkCenterDocument[] = [
  workCenter("wc-extrusion-a", "Extrusion Line A", 8, 16, [
    {
      startDate: iso(1, 12),
      endDate: iso(1, 14),
      reason: "New year calibration",
    },
    {
      startDate: iso(6, 10),
      endDate: iso(6, 11),
      reason: "Temperature profile audit",
    },
    {
      startDate: iso(15, 13),
      endDate: iso(15, 15),
      reason: "Screw inspection",
    },
    {
      startDate: iso(22, 11),
      endDate: iso(22, 12),
      reason: "Drive belt service",
    },
  ]),
  workCenter("wc-extrusion-b", "Extrusion Line B", 7, 15, [
    {
      startDate: iso(2, 11),
      endDate: iso(2, 12),
      reason: "Die head inspection",
    },
    {
      startDate: iso(8, 9),
      endDate: iso(8, 11),
      reason: "Mandrel alignment",
    },
    {
      startDate: iso(20, 13),
      endDate: iso(20, 14),
      reason: "Oil level service",
    },
  ]),
  workCenter("wc-cutting", "Cutting Station", 9, 17, [
    {
      startDate: iso(2, 10),
      endDate: iso(2, 11),
      reason: "Blade replacement",
    },
    {
      startDate: iso(9, 13),
      endDate: iso(9, 15),
      reason: "Guide rail service",
    },
    {
      startDate: iso(16, 9),
      endDate: iso(16, 10),
      reason: "Vacuum line check",
    },
    {
      startDate: iso(23, 14),
      endDate: iso(23, 16),
      reason: "Saw motor inspection",
    },
  ]),
  workCenter("wc-packaging", "Packaging Station", 10, 18, [
    {
      startDate: iso(2, 12),
      endDate: iso(2, 13),
      reason: "Label printer service",
    },
    {
      startDate: iso(7, 15),
      endDate: iso(7, 16),
      reason: "Sealer temperature check",
    },
    {
      startDate: iso(14, 10),
      endDate: iso(14, 12),
      reason: "Conveyor tune-up",
    },
    {
      startDate: iso(21, 13),
      endDate: iso(21, 14),
      reason: "Scanner calibration",
    },
  ]),
];

const manufacturingOrders: ManufacturingOrderDocument[] = [
  manufacturingOrder("mo-green-pipe", "MO-1001", "GREEN-PIPE-50MM", 3, iso(24, 17)),
  manufacturingOrder("mo-blue-pipe", "MO-1002", "BLUE-PIPE-75MM", 4, iso(26, 17)),
  manufacturingOrder("mo-yellow-pipe", "MO-1003", "YELLOW-PIPE-100MM", 2, iso(27, 17)),
  manufacturingOrder("mo-purple-valve", "MO-1004", "PURPLE-VALVE-20MM", 2, iso(22, 17)),
  manufacturingOrder("mo-orange-elbow", "MO-1005", "ORANGE-ELBOW-45D", 1, iso(17, 17)),
  manufacturingOrder("mo-silver-bracket", "MO-1006", "SILVER-BRACKET-L", 3, iso(29, 17)),
  manufacturingOrder("mo-red-gasket", "MO-1007", "RED-GASKET-SET", 5, iso(21, 17)),
  manufacturingOrder("mo-teal-hose", "MO-1008", "TEAL-HOSE-1M", 2, iso(25, 17)),
  manufacturingOrder("mo-amber-kit", "MO-1009", "AMBER-REPAIR-KIT", 2, iso(30, 17)),
  manufacturingOrder("mo-gray-cap", "MO-1010", "GRAY-END-CAP", 4, iso(18, 17)),
  manufacturingOrder("mo-white-adapter", "MO-1011", "WHITE-ADAPTER-M12", 2, iso(28, 17)),
  manufacturingOrder("mo-black-coupler", "MO-1012", "BLACK-COUPLER-32MM", 3, iso(23, 17)),
];

const workOrders: WorkOrderDocument[] = [
  workOrder({
    docId: "wo-green-extrude",
    workOrderNumber: "WO-1001-EX",
    manufacturingOrderId: "mo-green-pipe",
    workCenterId: "wc-extrusion-a",
    startDate: iso(1, 8),
    endDate: iso(12, 16),
    durationMinutes: 240,
  }),
  workOrder({
    docId: "wo-green-clean",
    workOrderNumber: "WO-1001-MNT",
    manufacturingOrderId: "mo-green-pipe",
    workCenterId: "wc-extrusion-a",
    startDate: iso(2, 8),
    endDate: iso(13, 16),
    durationMinutes: 45,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-green-extrude"],
  }),
  workOrder({
    docId: "wo-green-cut",
    workOrderNumber: "WO-1001-CUT",
    manufacturingOrderId: "mo-green-pipe",
    workCenterId: "wc-cutting",
    startDate: iso(3, 9),
    endDate: iso(16, 17),
    durationMinutes: 180,
    dependsOnWorkOrderIds: ["wo-green-clean"],
  }),
  workOrder({
    docId: "wo-green-pressure",
    workOrderNumber: "WO-1001-QA",
    manufacturingOrderId: "mo-green-pipe",
    workCenterId: "wc-cutting",
    startDate: iso(4, 9),
    endDate: iso(17, 17),
    durationMinutes: 120,
    dependsOnWorkOrderIds: ["wo-green-cut"],
  }),
  workOrder({
    docId: "wo-green-pack",
    workOrderNumber: "WO-1001-PACK",
    manufacturingOrderId: "mo-green-pipe",
    workCenterId: "wc-packaging",
    startDate: iso(5, 10),
    endDate: iso(20, 18),
    durationMinutes: 120,
    dependsOnWorkOrderIds: ["wo-green-pressure"],
  }),
  workOrder({
    docId: "wo-blue-extrude",
    workOrderNumber: "WO-1002-EX",
    manufacturingOrderId: "mo-blue-pipe",
    workCenterId: "wc-extrusion-b",
    startDate: iso(1, 7),
    endDate: iso(14, 15),
    durationMinutes: 360,
  }),
  workOrder({
    docId: "wo-blue-trim",
    workOrderNumber: "WO-1002-TRIM",
    manufacturingOrderId: "mo-blue-pipe",
    workCenterId: "wc-cutting",
    startDate: iso(2, 9),
    endDate: iso(18, 17),
    durationMinutes: 210,
    dependsOnWorkOrderIds: ["wo-blue-extrude"],
  }),
  workOrder({
    docId: "wo-blue-label-setup",
    workOrderNumber: "WO-1002-MNT",
    manufacturingOrderId: "mo-blue-pipe",
    workCenterId: "wc-packaging",
    startDate: iso(3, 10),
    endDate: iso(18, 18),
    durationMinutes: 60,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-blue-extrude"],
  }),
  workOrder({
    docId: "wo-blue-pack",
    workOrderNumber: "WO-1002-PACK",
    manufacturingOrderId: "mo-blue-pipe",
    workCenterId: "wc-packaging",
    startDate: iso(4, 10),
    endDate: iso(22, 18),
    durationMinutes: 150,
    dependsOnWorkOrderIds: ["wo-blue-trim", "wo-blue-label-setup"],
  }),
  workOrder({
    docId: "wo-blue-audit",
    workOrderNumber: "WO-1002-AUD",
    manufacturingOrderId: "mo-blue-pipe",
    workCenterId: "wc-packaging",
    startDate: iso(6, 10),
    endDate: iso(23, 18),
    durationMinutes: 45,
    dependsOnWorkOrderIds: ["wo-blue-pack"],
  }),
  workOrder({
    docId: "wo-yellow-extrude",
    workOrderNumber: "WO-1003-EX",
    manufacturingOrderId: "mo-yellow-pipe",
    workCenterId: "wc-extrusion-a",
    startDate: iso(4, 8),
    endDate: iso(16, 16),
    durationMinutes: 300,
  }),
  workOrder({
    docId: "wo-yellow-polish",
    workOrderNumber: "WO-1003-POL",
    manufacturingOrderId: "mo-yellow-pipe",
    workCenterId: "wc-cutting",
    startDate: iso(5, 9),
    endDate: iso(20, 17),
    durationMinutes: 240,
    dependsOnWorkOrderIds: ["wo-yellow-extrude"],
  }),
  workOrder({
    docId: "wo-yellow-pack",
    workOrderNumber: "WO-1003-PACK",
    manufacturingOrderId: "mo-yellow-pipe",
    workCenterId: "wc-packaging",
    startDate: iso(8, 10),
    endDate: iso(24, 18),
    durationMinutes: 180,
    dependsOnWorkOrderIds: ["wo-yellow-polish"],
  }),
  workOrder({
    docId: "wo-purple-machine",
    workOrderNumber: "WO-1004-MACH",
    manufacturingOrderId: "mo-purple-valve",
    workCenterId: "wc-extrusion-b",
    startDate: iso(2, 7),
    endDate: iso(13, 15),
    durationMinutes: 300,
  }),
  workOrder({
    docId: "wo-purple-calibrate",
    workOrderNumber: "WO-1004-MNT",
    manufacturingOrderId: "mo-purple-valve",
    workCenterId: "wc-extrusion-b",
    startDate: iso(3, 7),
    endDate: iso(15, 15),
    durationMinutes: 90,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-purple-machine"],
  }),
  workOrder({
    docId: "wo-purple-cut",
    workOrderNumber: "WO-1004-CUT",
    manufacturingOrderId: "mo-purple-valve",
    workCenterId: "wc-cutting",
    startDate: iso(4, 9),
    endDate: iso(17, 17),
    durationMinutes: 150,
    dependsOnWorkOrderIds: ["wo-purple-calibrate"],
  }),
  workOrder({
    docId: "wo-purple-pack",
    workOrderNumber: "WO-1004-PACK",
    manufacturingOrderId: "mo-purple-valve",
    workCenterId: "wc-packaging",
    startDate: iso(6, 10),
    endDate: iso(20, 18),
    durationMinutes: 90,
    dependsOnWorkOrderIds: ["wo-purple-cut"],
  }),
  workOrder({
    docId: "wo-orange-bend",
    workOrderNumber: "WO-1005-BEND",
    manufacturingOrderId: "mo-orange-elbow",
    workCenterId: "wc-extrusion-b",
    startDate: iso(1, 7),
    endDate: iso(16, 15),
    durationMinutes: 210,
  }),
  workOrder({
    docId: "wo-silver-plate",
    workOrderNumber: "WO-1006-PLATE",
    manufacturingOrderId: "mo-silver-bracket",
    workCenterId: "wc-extrusion-a",
    startDate: iso(5, 8),
    endDate: iso(20, 16),
    durationMinutes: 240,
  }),
  workOrder({
    docId: "wo-silver-drill",
    workOrderNumber: "WO-1006-DRILL",
    manufacturingOrderId: "mo-silver-bracket",
    workCenterId: "wc-cutting",
    startDate: iso(5, 9),
    endDate: iso(22, 17),
    durationMinutes: 240,
  }),
  workOrder({
    docId: "wo-silver-deburr",
    workOrderNumber: "WO-1006-MNT",
    manufacturingOrderId: "mo-silver-bracket",
    workCenterId: "wc-cutting",
    startDate: iso(8, 9),
    endDate: iso(23, 17),
    durationMinutes: 60,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-silver-drill"],
  }),
  workOrder({
    docId: "wo-silver-pack",
    workOrderNumber: "WO-1006-PACK",
    manufacturingOrderId: "mo-silver-bracket",
    workCenterId: "wc-packaging",
    startDate: iso(10, 10),
    endDate: iso(27, 18),
    durationMinutes: 120,
    dependsOnWorkOrderIds: ["wo-silver-plate", "wo-silver-deburr"],
  }),
  workOrder({
    docId: "wo-red-stamp",
    workOrderNumber: "WO-1007-STAMP",
    manufacturingOrderId: "mo-red-gasket",
    workCenterId: "wc-cutting",
    startDate: iso(3, 9),
    endDate: iso(19, 17),
    durationMinutes: 75,
  }),
  workOrder({
    docId: "wo-teal-extrude",
    workOrderNumber: "WO-1008-EX",
    manufacturingOrderId: "mo-teal-hose",
    workCenterId: "wc-extrusion-b",
    startDate: iso(6, 7),
    endDate: iso(18, 15),
    durationMinutes: 240,
  }),
  workOrder({
    docId: "wo-teal-sanitize",
    workOrderNumber: "WO-1008-MNT",
    manufacturingOrderId: "mo-teal-hose",
    workCenterId: "wc-extrusion-b",
    startDate: iso(7, 7),
    endDate: iso(20, 15),
    durationMinutes: 45,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-teal-extrude"],
  }),
  workOrder({
    docId: "wo-teal-pack",
    workOrderNumber: "WO-1008-PACK",
    manufacturingOrderId: "mo-teal-hose",
    workCenterId: "wc-packaging",
    startDate: iso(9, 10),
    endDate: iso(24, 18),
    durationMinutes: 120,
    dependsOnWorkOrderIds: ["wo-teal-sanitize"],
  }),
  workOrder({
    docId: "wo-amber-shell",
    workOrderNumber: "WO-1009-SHELL",
    manufacturingOrderId: "mo-amber-kit",
    workCenterId: "wc-extrusion-a",
    startDate: iso(7, 8),
    endDate: iso(22, 16),
    durationMinutes: 180,
  }),
  workOrder({
    docId: "wo-amber-insert",
    workOrderNumber: "WO-1009-INSERT",
    manufacturingOrderId: "mo-amber-kit",
    workCenterId: "wc-cutting",
    startDate: iso(7, 9),
    endDate: iso(23, 17),
    durationMinutes: 210,
  }),
  workOrder({
    docId: "wo-amber-setup",
    workOrderNumber: "WO-1009-MNT",
    manufacturingOrderId: "mo-amber-kit",
    workCenterId: "wc-packaging",
    startDate: iso(8, 10),
    endDate: iso(24, 18),
    durationMinutes: 60,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-amber-shell", "wo-amber-insert"],
  }),
  workOrder({
    docId: "wo-amber-pack",
    workOrderNumber: "WO-1009-PACK",
    manufacturingOrderId: "mo-amber-kit",
    workCenterId: "wc-packaging",
    startDate: iso(10, 10),
    endDate: iso(28, 18),
    durationMinutes: 240,
    dependsOnWorkOrderIds: ["wo-amber-setup"],
  }),
  workOrder({
    docId: "wo-amber-audit",
    workOrderNumber: "WO-1009-AUD",
    manufacturingOrderId: "mo-amber-kit",
    workCenterId: "wc-packaging",
    startDate: iso(12, 10),
    endDate: iso(29, 18),
    durationMinutes: 90,
    dependsOnWorkOrderIds: ["wo-amber-pack"],
  }),
  workOrder({
    docId: "wo-gray-cap-mold",
    workOrderNumber: "WO-1010-MOLD",
    manufacturingOrderId: "mo-gray-cap",
    workCenterId: "wc-extrusion-a",
    startDate: iso(2, 8),
    endDate: iso(17, 16),
    durationMinutes: 60,
  }),
  workOrder({
    docId: "wo-white-extrude",
    workOrderNumber: "WO-1011-EX",
    manufacturingOrderId: "mo-white-adapter",
    workCenterId: "wc-extrusion-b",
    startDate: iso(9, 7),
    endDate: iso(24, 15),
    durationMinutes: 300,
  }),
  workOrder({
    docId: "wo-white-bore",
    workOrderNumber: "WO-1011-BORE",
    manufacturingOrderId: "mo-white-adapter",
    workCenterId: "wc-cutting",
    startDate: iso(10, 9),
    endDate: iso(25, 17),
    durationMinutes: 180,
    dependsOnWorkOrderIds: ["wo-white-extrude"],
  }),
  workOrder({
    docId: "wo-white-clean",
    workOrderNumber: "WO-1011-MNT",
    manufacturingOrderId: "mo-white-adapter",
    workCenterId: "wc-cutting",
    startDate: iso(11, 9),
    endDate: iso(26, 17),
    durationMinutes: 60,
    isMaintenance: true,
    dependsOnWorkOrderIds: ["wo-white-bore"],
  }),
  workOrder({
    docId: "wo-white-pack",
    workOrderNumber: "WO-1011-PACK",
    manufacturingOrderId: "mo-white-adapter",
    workCenterId: "wc-packaging",
    startDate: iso(12, 10),
    endDate: iso(28, 18),
    durationMinutes: 120,
    dependsOnWorkOrderIds: ["wo-white-clean"],
  }),
  workOrder({
    docId: "wo-black-mold",
    workOrderNumber: "WO-1012-MOLD",
    manufacturingOrderId: "mo-black-coupler",
    workCenterId: "wc-extrusion-a",
    startDate: iso(4, 8),
    endDate: iso(18, 16),
    durationMinutes: 210,
  }),
  workOrder({
    docId: "wo-black-cut",
    workOrderNumber: "WO-1012-CUT",
    manufacturingOrderId: "mo-black-coupler",
    workCenterId: "wc-cutting",
    startDate: iso(6, 9),
    endDate: iso(20, 17),
    durationMinutes: 120,
    dependsOnWorkOrderIds: ["wo-black-mold"],
  }),
  workOrder({
    docId: "wo-black-pack",
    workOrderNumber: "WO-1012-PACK",
    manufacturingOrderId: "mo-black-coupler",
    workCenterId: "wc-packaging",
    startDate: iso(8, 10),
    endDate: iso(23, 18),
    durationMinutes: 90,
    dependsOnWorkOrderIds: ["wo-black-cut"],
  }),
];

export const basicScheduleInput = {
  config: {
    horizonStartDate: "2026-01-01T00:00:00.000Z",
    horizonEndDate: "2026-02-01T00:00:00.000Z",
  },
  workCenters,
  manufacturingOrders,
  workOrders,
} satisfies PrepareScheduleInput;

export const basicScheduleScenarioNotes = [
  "Exactly four work centers are used: two extrusion lines, one cutting station, and one packaging station.",
  "Twelve manufacturing orders cover chains, branches, joins, and single-node DAGs.",
  "Manufacturing quantities range from 1 to 5, expanding the graph into more than one hundred execution nodes.",
  "Work order start and end dates are wide placement windows with varied starts, deadlines, and durations.",
  "Maintenance-type work orders are dependency nodes in the initial schedule and fixed executions during delay reflow.",
  "Several work centers share downstream cutting and packaging pressure, which exercises the balancing heuristic.",
  "Maintenance windows split availability independently from maintenance-type work orders.",
  "Downstream work orders wait for their dependency finish times even across work centers.",
];
